CREATE TABLE [nuu].[AltiboxMobil_Nuuday] (

	[TCM Kunde ID] bigint NOT NULL, 
	[Bevægelse] varchar(100) NULL, 
	[Status] varchar(100) NULL, 
	[Produkt Type] varchar(100) NULL, 
	[Produkt ID] int NULL, 
	[Abonnements ID] int NULL, 
	[Eksternt abonnnementsnavn] varchar(200) NULL, 
	[Internt abonnnementsnavn] varchar(200) NULL, 
	[Familieabonnement til produkt-id] varchar(200) NULL, 
	[Mobil nummer] varchar(100) NULL, 
	[E-Mail] varchar(200) NULL, 
	[Sælgerreference] varchar(200) NULL, 
	[Tidligere udbyder] varchar(200) NULL, 
	[Kunde Navn] varchar(200) NULL, 
	[Kunde Adresse] varchar(300) NULL, 
	[Kunde Postnummer] varchar(50) NULL, 
	[Kunde By] varchar(100) NULL, 
	[Permission] varchar(50) NULL, 
	[Bestillingstid] varchar(100) NULL, 
	[Aktiveringsdato] date NULL, 
	[Afregningstype] varchar(100) NULL, 
	[Automatisk optankning] varchar(100) NULL, 
	[Registrering af opsigelsesdato] varchar(200) NULL, 
	[Opsigelsesdato] date NULL, 
	[Kommentar til opsigelse] varchar(300) NULL, 
	[Udporteringsdato] date NULL, 
	[Eksport til] varchar(200) NULL, 
	[Tilvalg] varchar(200) NULL, 
	[Bindingsperiode slutter] date NULL, 
	[Bundles på købstidspunkt] varchar(200) NULL, 
	[Bestillingsdato] date NULL, 
	[FromDate] date NULL, 
	[ToDate] date NULL, 
	[LastVersion] int NULL
);