CREATE TABLE [nuu].[AltiboxMobil_Nuuday] (
    [TCM Kunde ID]                     BIGINT        NOT NULL,
    [Bevægelse]                        VARCHAR (100) NULL,
    [Status]                           VARCHAR (100) NULL,
    [Produkt Type]                     VARCHAR (100) NULL,
    [Produkt ID]                       INT           NULL,
    [Abonnements ID]                   INT           NULL,
    [Eksternt abonnnementsnavn]        VARCHAR (200) NULL,
    [Internt abonnnementsnavn]         VARCHAR (200) NULL,
    [Familieabonnement til produkt-id] VARCHAR (200) NULL,
    [Mobil nummer]                     VARCHAR (100) NULL,
    [E-Mail]                           VARCHAR (200) NULL,
    [Sælgerreference]                  VARCHAR (200) NULL,
    [Tidligere udbyder]                VARCHAR (200) NULL,
    [Kunde Navn]                       VARCHAR (200) NULL,
    [Kunde Adresse]                    VARCHAR (300) NULL,
    [Kunde Postnummer]                 VARCHAR (50)  NULL,
    [Kunde By]                         VARCHAR (100) NULL,
    [Permission]                       VARCHAR (50)  NULL,
    [Bestillingstid]                   VARCHAR (100) NULL,
    [Aktiveringsdato]                  DATE          NULL,
    [Afregningstype]                   VARCHAR (100) NULL,
    [Automatisk optankning]            VARCHAR (100) NULL,
    [Registrering af opsigelsesdato]   VARCHAR (200) NULL,
    [Opsigelsesdato]                   DATE          NULL,
    [Kommentar til opsigelse]          VARCHAR (300) NULL,
    [Udporteringsdato]                 DATE          NULL,
    [Eksport til]                      VARCHAR (200) NULL,
    [Tilvalg]                          VARCHAR (200) NULL,
    [Bindingsperiode slutter]          DATE          NULL,
    [Bundles på købstidspunkt]         VARCHAR (200) NULL,
    [Bestillingsdato]                  DATE          NULL,
    [FromDate]                         DATE          NULL,
    [ToDate]                           DATE          NULL,
    [LastVersion]                      INT           NULL
);


GO