table 'All Measures'
	lineageTag: 02659c75-af57-4f2e-a0bd-c985a4d1083d

	measure 'Antal Aktive Kunder' = Calculate(DISTINCTCOUNT('Status_I_dag_'[KundeNO]),'Status_I_dag_'[Kunde_Status]="Aktive")
		formatString: 0
		lineageTag: 08639b64-d711-4626-8a7f-025ccd36a6fe

	measure 'Antal Aktive Produkter' = Calculate(COUNT('Status_I_dag_'[ProduktID]),'Status_I_dag_'[Produkt_Status]="I brug")
		formatString: 0
		lineageTag: 2c5058de-db8b-42ed-86bd-54c7147df39d

		changedProperty = Name

	measure 'Antal Churned Kunder' = Calculate(DISTINCTCOUNT('Status_I_dag_'[KundeNO]),'Status_I_dag_'[Kunde_Status]="Churned")
		lineageTag: 895d6e82-4e9e-497e-9bc4-2144b2b514fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Antal Churned Produkter' = Calculate(COUNT('Status_I_dag_'[ProduktID]),'Status_I_dag_'[Produkt_Status]="Deaktiveret")
		formatString: 0
		lineageTag: 254dc0fb-108a-4b45-b3a6-9de946752e20

		changedProperty = Name

	measure 'Antal Kunder' = DISTINCTCOUNT('Status_I_dag_'[KundeNO])
		formatString: 0
		lineageTag: ab628c74-a784-4988-9957-29a74e6e3ec4

		changedProperty = Name

	measure 'Antal Pending Kunder' = Calculate(DISTINCTCOUNT('Status_i_dag_'[KundeNO]),'Status_i_dag_'[Kunde_Status]="Pending")
		formatString: 0
		lineageTag: 1c8c2932-32e3-4e83-8eed-dfd4b9038d1f

	measure 'Antal Pending Produkter' = ```
			Calculate(COUNT('Status_i_dag_'[ProduktID]),'Status_i_dag_'[Produkt_Status]="Pending")
			
			```
		formatString: 0
		lineageTag: 67dc0ed0-2e82-4401-9ce9-d54dc8c9e39b

		changedProperty = Name

	measure 'Antal Produkter' = COUNT('Status_i_dag_'[ProduktID])
		formatString: 0
		lineageTag: d7cb69cb-06b6-4bb1-8d3a-90fb25245343

		changedProperty = Name

	measure 'Antal MedlemNr' = DISTINCTCOUNT('Customer'[memberNumber])
		formatString: 0
		lineageTag: 4ca31d39-9503-4499-b687-6c06499292e3

	measure 'Kunder med NySalg' = Calculate(DISTINCTCOUNT('Status_I_dag_'[KundeNO]),'Status_I_dag_'[NySalg]=TRUE())
		formatString: 0
		lineageTag: 044ec9ae-b7d0-412d-a07f-db3588f579f5

	measure 'Antal NySalg Produkter' = Calculate(COUNT('Status_I_dag_'[ProduktID]),'Status_I_dag_'[NySalg]=TRUE())
		formatString: 0
		lineageTag: b777a041-6166-4428-ad4e-1f7698b9f768

	measure 'Accumulated NySalg Customers' =
			
			VAR MaxEndDate = MAX('Kalendar'[Date])
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('Status_I_dag_'[KundeNO]),
			    'Status_I_dag_'[NySalg] = TRUE(),
			    REMOVEFILTERS('Kalendar'),
			    'Kalendar'[Date] <= MaxEndDate
			)
		formatString: 0
		lineageTag: 6819672b-f503-4284-85c8-620bc3455d40

	column Measures
		dataType: string
		isHidden
		lineageTag: 62108bb9-bccb-48d6-be61-b76abfa9f2b5
		summarizeBy: none
		sourceColumn: Measures

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'All Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measures", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

