CREATE TABLE [puz].[agent_events] (

	[rec_id] int NULL, 
	[agent_id] int NULL, 
	[dte_start] datetime2(6) NULL, 
	[profile] varchar(8000) NULL, 
	[service_num] varchar(8000) NULL, 
	[phone_num] varchar(8000) NULL, 
	[duration_sec] int NULL, 
	[event_type] varchar(8000) NULL, 
	[event_source] varchar(8000) NULL, 
	[result_code] varchar(8000) NULL, 
	[queue_key] varchar(8000) NULL, 
	[pause_type_name] varchar(8000) NULL, 
	[pause_type_id] int NULL, 
	[call_transfer] bit NULL, 
	[wrap_up_sec] int NULL, 
	[block_duration_sec] int NULL, 
	[internal_adr_id] bigint NULL, 
	[internal_odr_id] bigint NULL, 
	[internal_country_src_db] varchar(8000) NULL, 
	[dte_updated] datetime2(6) NULL, 
	[usergroup_id] int NULL, 
	[phone_type] int NULL, 
	[dte_start_time] time(0) NULL, 
	[dte_start_hour] int NULL, 
	[dte_start_minute] int NULL, 
	[dte_start_index] int NULL
);