CREATE TABLE [puz].[vw_enqreg_total] (

	[enqreg_header_recid] int NULL, 
	[internal_session_id] varchar(8000) NULL, 
	[customer_key] varchar(8000) NULL, 
	[internal_country_src_db] varchar(8000) NULL, 
	[dte_time_stamp] datetime2(6) NULL, 
	[agent_id] int NULL, 
	[queue_key] varchar(8000) NULL, 
	[enquiry_media_type] varchar(8000) NULL, 
	[related_iq_session_id] varchar(8000) NULL, 
	[dte_updated] datetime2(6) NULL, 
	[comment] varchar(8000) NULL, 
	[reschedule_time] datetime2(6) NULL, 
	[enqreg_category_recid] int NULL, 
	[category_id] int NULL, 
	[category_name] varchar(8000) NULL, 
	[enqreg_topic_recid] int NULL, 
	[topic_id] int NULL, 
	[topic_name] varchar(8000) NULL, 
	[marked_unansw] varchar(8000) NULL, 
	[reserved] varchar(8000) NULL, 
	[parsed_category_id] varchar(8000) NULL, 
	[parsed_category_name] varchar(8000) NULL, 
	[dte_start_time] time(0) NULL, 
	[dte_start_hour] int NULL, 
	[dte_start_minute] int NULL, 
	[dte_start_index] int NULL, 
	[dte_start_date] date NULL
);